name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "npm"
      - name: Install npm@9
        run: npm i -g npm@9
      - name: Install
        run: npm ci --prefer-offline
      - name: Eslint
        run: npm run lint -- --max-warnings 0
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
